/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const DecodeHtml: typeof import('./resources/js/composables/markdown.js')['DecodeHtml']
  const HtmlToMarkdown: typeof import('./resources/js/composables/markdown.js')['HtmlToMarkdown']
  const Link: typeof import('@inertiajs/vue3')['Link']
  const MarkdownToHtml: typeof import('./resources/js/composables/markdown.js')['MarkdownToHtml']
  const computed: typeof import('vue')['computed']
  const currentTheme: typeof import('./resources/js/composables/themeAdapter.js')['currentTheme']
  const defineEmits: typeof import('vue')['defineEmits']
  const detectFormat: typeof import('./resources/js/composables/markdown.js')['detectFormat']
  const getImageUrl: typeof import('./resources/js/composables/utils.js')['getImageUrl']
  const nextTick: typeof import('vue')['nextTick']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onMounted: typeof import('vue')['onMounted']
  const onThemeChange: typeof import('./resources/js/composables/themeAdapter.js')['onThemeChange']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const parseAudios: typeof import('./resources/js/composables/parseAudios.js')['parseAudios']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const router: typeof import('@inertiajs/vue3')['router']
  const updateTheme: typeof import('./resources/js/composables/themeAdapter.js')['updateTheme']
  const useForm: typeof import('@inertiajs/vue3')['useForm']
  const usePage: typeof import('@inertiajs/vue3')['usePage']
  const useSlots: typeof import('vue')['useSlots']
  const watch: typeof import('vue')['watch']
}
