/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const Link: typeof import('@inertiajs/vue3')['Link']
  const computed: typeof import('vue')['computed']
  const defineEmits: typeof import('vue')['defineEmits']
  const nextTick: typeof import('vue')['nextTick']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const router: typeof import('@inertiajs/vue3')['router']
  const useForm: typeof import('@inertiajs/vue3')['useForm']
  const usePage: typeof import('@inertiajs/vue3')['usePage']
  const useSlots: typeof import('vue')['useSlots']
  const watch: typeof import('vue')['watch']
}
