<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html lang='es-ES'>
<head>
<meta charset="UTF-8" />
<title>PHPWord</title>
<meta name="author" content="Manuel Cerezo" />
<style>
body {font-family: 'Arial'; font-size: 11pt;}
* {font-family: 'Arial'; font-size: 11pt;}
a.NoteRef {text-decoration: none;}
hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
table {border: 1px solid black; border-spacing: 0px; width : 100%;}
td {border: 1px solid black;}
p, .Normal {margin-bottom: 8pt;}
.Normal Table {table-layout: auto;}
.List Paragraph {margin-left: 360in; margin-right: 0in;}
.header {margin-bottom: 0pt;}
.footer {margin-bottom: 0pt;}
body > div + div {page-break-before: always;}
div > *:first-child {page-break-before: auto;}
@page page1 {size: A4 portrait; margin-right: 1.18125in; margin-left: 1.18125in; margin-top: 0.98402777777778in; margin-bottom: 0.98402777777778in; }
</style>
</head>
<body>
<div style='page: page1'>
<p style="text-align: center;"><span style="font-size: 14pt; font-weight: bold;">PROGRAMA DE LAS </span><span style="font-size: 14pt; font-weight: bold;">CONVIVENCIAS </span><span style="font-size: 14pt; font-weight: bold;">DE </span><span style="font-size: 14pt; font-weight: bold;">ABRIL </span><span style="font-size: 14pt; font-weight: bold;">EN </span><span style="font-size: 14pt; font-weight: bold;">TEGOYO</span></p>
<p style="text-align: center;"><span style="font-size: 14pt; font-weight: bold;">IXº</span><span style="font-size: 14pt; font-weight: bold;"> ANIVERSARIO DEL MUULASTERIO TSEYOR EN TIAGUA</span></p>
<p style="text-align: center;"><span style="font-size: 14pt; font-weight: bold;">Miércoles </span><span style="font-size: 14pt; font-weight: bold;">2</span><span style="font-size: 14pt; font-weight: bold;">4</span><span style="font-size: 14pt; font-weight: bold;"> a sábado 27 de abril </span><span style="font-size: 14pt; font-weight: bold;">2024</span></p>
<p style="text-align: center;"><span style="font-size: 14pt; font-weight: bold;">Lema: </span><span style="font-size: 14pt; font-weight: bold; font-style: italic;">Conectados con La Llamada </span> </p>
<p>&nbsp;</p>
<p><span style="font-size: 14pt;">Las sesiones de las </span></p>
<p><span style="font-size: 14pt;">co</span></p>
<p><span style="font-size: 14pt;">nvivencias se </span></p>
<p><span style="font-size: 14pt;">t</span></p>
<p><span style="font-size: 14pt;">ransmitirán por la sala </span></p>
<p><span style="font-size: 14pt; font-style: italic;">Muulasterio</span></p>
<p><span style="font-size: 14pt; font-style: italic;">&nbsp;</span></p>
<p><span style="font-size: 14pt; font-style: italic;">Tseyor</span></p>
<p><span style="font-size: 14pt; font-style: italic;">&nbsp;</span></p>
<p><span style="font-size: 14pt; font-style: italic;">Tegoyo</span></p>
<p><span style="font-size: 14pt;"> de </span></p>
<p><span style="font-size: 14pt;">Paltalk</span></p>
<p><span style="font-size: 14pt;"> en horario de tarde</span></p>

<p><span style="font-size: 14pt;">Los HH. MM. podrán intervenir </span></p>
<p><span style="font-size: 14pt;">por las tardes </span></p>
<p><span style="font-size: 14pt;">a través del canal de Puente, que estará disponible </span></p>

<p>&nbsp;</p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-weight: bold;">Miércoles 24</span><span style="font-size: 14pt; font-weight: bold;"> </span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-style: italic;">Mañana</span><span style="font-size: 14pt;">: 11 a 13:30 h. </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Mañana</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">: </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Inauguración de las convivencias</span></p>

<p><span style="font-size: 14pt; font-weight: bold;">Observación de la lámina de las convivencias</span></p>

<p><span style="font-size: 14pt; font-weight: bold;">Trabajo con las Cartas de </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Uommo</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">&nbsp;</span></p>

<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-style: italic;">Tarde</span><span style="font-size: 14pt;">: 17 a 19 h. de Canarias y 18 a 20:30 h. España peninsular</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Red de intercambio de bienes y servicios: actualización</span></p>

<p><span style="font-size: 14pt; font-weight: bold;">Lectura del TAP 161 de </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Shilcars</span></p>
<p><span style="font-size: 14pt; font-weight: bold;"> La ONG instrumento de ayuda humanitaria</span></p>

<p><span style="font-size: 14pt; font-weight: bold;">Espacio para la intervención de los hermanos mayores</span></p>

<p><span style="font-size: 14pt; font-weight: bold;">19 h. </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Asamblea de socios de la ONG</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">&nbsp;</span></p>

<p>&nbsp;</p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-weight: bold;">Jueves 25</span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-style: italic;">Mañana</span><span style="font-size: 14pt;">: 11 a 13:30 h. de Canarias o 12 h. a 14:30 España peninsular</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">El </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Muulasterio</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">&nbsp;</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Tseyor</span></p>
<p><span style="font-size: 14pt; font-weight: bold;"> como centro de conexión </span></p>

<p><span style="font-size: 14pt; font-weight: bold;">Lectura del comunicado del Aniversario del año anterior</span></p>
<p><span style="font-size: 14pt; font-weight: bold;"> TAP 195 </span></p>
<p><span style="font-size: 14pt; font-style: italic;">Suma y sigue la hermandad</span></p>

<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-style: italic;">Tarde</span><span style="font-size: 14pt;">: 1</span><span style="font-size: 14pt;">6</span><span style="font-size: 14pt;"> a 1</span><span style="font-size: 14pt;">8</span><span style="font-size: 14pt;">:30 h. de Canarias y 1</span><span style="font-size: 14pt;">7</span><span style="font-size: 14pt;"> a </span><span style="font-size: 14pt;">19</span><span style="font-size: 14pt;">:30 h. España peninsular</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Conmemoración del </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">IXª</span></p>
<p><span style="font-size: 14pt; font-weight: bold;"> Aniversario del </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Muulasterio</span></p>
<p><span style="font-size: 14pt; font-weight: bold;"> en Tigua</span></p>

<p><span style="font-size: 14pt; font-weight: bold;">Retrospectiva y prospectiva</span></p>

<p><span style="font-size: 14pt; font-weight: bold;">Espacio para la intervención de los hermanos mayores</span></p>

<p>&nbsp;</p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-weight: bold;">Viernes 26</span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-style: italic;">Mañana</span><span style="font-size: 14pt;">: 11 a 13:30 h. de Canarias o 12 h. a 14:30 España peninsular</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">La divulgación</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">: los caminos de la divulgación</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">&nbsp;</span></p>

<p><span style="font-size: 14pt; font-weight: bold;">Experiencias de divulgación</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">&nbsp;</span></p>

<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-style: italic;">Tarde</span><span style="font-size: 14pt;">: 1</span><span style="font-size: 14pt;">6:30</span><span style="font-size: 14pt;"> a 1</span><span style="font-size: 14pt;">8</span><span style="font-size: 14pt;">:30 h. de Canarias y 18 a 20:30 h. España peninsular</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Visita al Volcán de </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Tamia</span></p>

<p><span style="font-size: 14pt; font-weight: bold;">19 h Extrapolación y rescate adimensional </span></p>

<p><span style="font-size: 14pt; font-weight: bold;">Espacio para la intervención de los hermanos mayores</span></p>

<p>&nbsp;</p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-weight: bold;">Sábado 27</span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-style: italic;">Mañana</span><span style="font-size: 14pt;">: 1</span><span style="font-size: 14pt;">1 a 13:30</span><span style="font-size: 14pt;"> h. </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Proyecto SAR </span></p>

<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-style: italic;">T</span><span style="font-size: 14pt; font-style: italic;">arde</span><span style="font-size: 14pt;">: 17 a 19</span><span style="font-size: 14pt;">:30</span><span style="font-size: 14pt;"> h. de Canarias y 18 a 20:30 h. España peninsular</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Conclusiones </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">de las Convivencias</span></p>

<p><span style="font-size: 14pt; font-weight: bold;">Taller de reconocimiento</span></p>
<p><span style="font-size: 14pt; font-weight: bold;"> por </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Shilcars</span></p>

<p><span style="font-size: 14pt; font-weight: bold;">Ceremonia de </span></p>
<p><span style="font-size: 14pt; font-weight: bold;">Energetización</span></p>
<p><span style="font-size: 14pt; font-weight: bold;"> de agua, piedra</span></p>
<p><span style="font-size: 14pt; font-weight: bold;">s,</span></p>
<p><span style="font-size: 14pt; font-weight: bold;"> semillas y elementos </span></p>

<p>&nbsp;</p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-weight: bold;">HORARIO COTIDIANO</span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt;">Meditaciones matutinas: 8:30 h. </span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt;">Desayuno: 9 h. </span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt;">Almuerzo: 14 horas (servido por </span><span style="font-size: 14pt; font-style: italic;">catering</span><span style="font-size: 14pt;">)</span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt;">Cena: 20:30 h</span><span style="font-size: 14pt;">. </span><span style="font-size: 14pt;"> </span></p>
<p>&nbsp;</p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt; font-weight: bold;">COSTES DE ASISTENCIA</span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt;">Pernoctación: </span><span style="font-size: 14pt;">4 € o </span><span style="font-size: 14pt;">muul</span><span style="font-size: 14pt;">are</span><span style="font-size: 14pt;">s</span><span style="font-size: 14pt;"> por persona y día</span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt;">Desayuno: 4 € o </span><span style="font-size: 14pt;">muul</span><span style="font-size: 14pt;">are</span><span style="font-size: 14pt;">s</span><span style="font-size: 14pt;"> por persona y día</span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt;">Almuerzo: coste del </span><span style="font-size: 14pt; font-style: italic;">catering</span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt;">Cena: 4 € o </span><span style="font-size: 14pt;">muul</span><span style="font-size: 14pt;">are</span><span style="font-size: 14pt;">s</span><span style="font-size: 14pt;"> por persona y día</span></p>
<p style="margin-bottom: 6pt;"><span style="font-size: 14pt;">Logística: 5 € por persona, pago único</span></p>
<p><span style="font-size: 14pt;">Ingreso del importe de las convivencias en la cuenta del </span></p>
<p><span style="font-size: 14pt;">Muulasterio</span></p>
<p><span style="font-size: 14pt;"> CaixaBank </span></p>
<p><span style="font-family: 'Calibri'; font-size: 14pt;">IBAN ES84 2100 6869 0702 0007 9291 </span></p>

<p>&nbsp;</p>
</div>
</body>
</html>