<?php
// MCP/campos.php

return [
    'comunicado' => [
        'titulo' => ['type' => 'string', 'description' => 'Título del comunicado'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'texto' => ['type' => 'string', 'description' => 'Contenido en markdown'],
        'fecha_comunicado' => ['type' => 'string', 'description' => 'Fecha (YYYY-MM-DD)'],
        'categoria' => ['type' => 'int', 'description' => 'Categoría numérica (0=General, 1=TAP, 2=12 del M., 3=Muul)'],
        'ano' => ['type' => 'int', 'description' => 'Año'],
        'imagen' => ['type' => 'string', 'description' => 'Ruta o URL de la imagen'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
    ],
    'entrada' => [
        'titulo' => ['type' => 'string', 'description' => 'Título de la entrada'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'texto' => ['type' => 'string', 'description' => 'Contenido en markdown'],
        'published_at' => ['type' => 'string', 'description' => 'Fecha de publicación (YYYY-MM-DD)'],
        'imagen' => ['type' => 'string', 'description' => 'Ruta o URL de la imagen'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
    ],
    'noticia' => [
        'titulo' => ['type' => 'string', 'description' => 'Título de la noticia'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'texto' => ['type' => 'string', 'description' => 'Contenido en markdown'],
        'published_at' => ['type' => 'string', 'description' => 'Fecha de publicación (YYYY-MM-DD)'],
        'imagen' => ['type' => 'string', 'description' => 'Ruta o URL de la imagen'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
    ],
    'audio' => [
        'titulo' => ['type' => 'string', 'description' => 'Título del audio'],
        'slug' => ['type' => 'string', 'description' => 'Slug único'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'categoria' => ['type' => 'string', 'description' => 'Categoría del audio'],
        'enlace' => ['type' => 'string', 'description' => 'Enlace externo (opcional)'],
        'audio' => ['type' => 'string', 'description' => 'Ruta o URL del archivo de audio'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
        'duracion' => ['type' => 'string', 'description' => 'Duración del audio (opcional)'],
    ],
    'centro' => [
        'nombre' => ['type' => 'string', 'description' => 'Nombre del centro'],
        'slug' => ['type' => 'string', 'description' => 'Slug único'],
        'imagen' => ['type' => 'string', 'description' => 'Ruta o URL de la imagen'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'entradas' => ['type' => 'int', 'description' => 'Número de entradas asociadas'],
        'libros' => ['type' => 'int', 'description' => 'Número de libros asociados'],
        'poblacion' => ['type' => 'string', 'description' => 'Población'],
        'pais' => ['type' => 'string', 'description' => 'Código de país'],
        'contacto_id' => ['type' => 'int', 'description' => 'ID del contacto asociado'],
    ],
    'contacto' => [
        'nombre' => ['type' => 'string', 'description' => 'Nombre del contacto'],
        'slug' => ['type' => 'string', 'description' => 'Slug único'],
        'imagen' => ['type' => 'string', 'description' => 'Ruta o URL de la imagen'],
        'pais' => ['type' => 'string', 'description' => 'Código de país'],
        'poblacion' => ['type' => 'string', 'description' => 'Población'],
        'provincia' => ['type' => 'string', 'description' => 'Provincia'],
        'direccion' => ['type' => 'string', 'description' => 'Dirección'],
        'codigo' => ['type' => 'string', 'description' => 'Código postal'],
        'telefono' => ['type' => 'string', 'description' => 'Teléfono'],
        'social' => ['type' => 'string', 'description' => 'Redes sociales'],
        'email' => ['type' => 'string', 'description' => 'Correo electrónico'],
        'latitud' => ['type' => 'string', 'description' => 'Latitud'],
        'longitud' => ['type' => 'string', 'description' => 'Longitud'],
        'centro_id' => ['type' => 'int', 'description' => 'ID del centro asociado'],
        'user_id' => ['type' => 'int', 'description' => 'ID del usuario asociado'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
    ],
    'equipo' => [
        'nombre' => ['type' => 'string', 'description' => 'Nombre del equipo'],
        'slug' => ['type' => 'string', 'description' => 'Slug único'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'imagen' => ['type' => 'string', 'description' => 'Ruta o URL de la imagen'],
        'categoria' => ['type' => 'string', 'description' => 'Categoría del equipo'],
        'group_id' => ['type' => 'int', 'description' => 'ID del grupo asociado'],
        'anuncio' => ['type' => 'string', 'description' => 'Anuncio del equipo'],
        'reuniones' => ['type' => 'string', 'description' => 'Información sobre reuniones'],
        'informacion' => ['type' => 'string', 'description' => 'Información adicional'],
        'oculto' => ['type' => 'boolean', 'description' => 'Si el equipo está oculto'],
        'ocultarCarpetas' => ['type' => 'boolean', 'description' => 'Ocultar carpetas asociadas'],
        'ocultarArchivos' => ['type' => 'boolean', 'description' => 'Ocultar archivos asociados'],
        'ocultarMiembros' => ['type' => 'boolean', 'description' => 'Ocultar miembros del equipo'],
        'ocultarSolicitudes' => ['type' => 'boolean', 'description' => 'Ocultar solicitudes de membresía'],
    ],
    'evento' => [
        'titulo' => ['type' => 'string', 'description' => 'Título del evento'],
        'slug' => ['type' => 'string', 'description' => 'Slug único'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'categoria' => ['type' => 'string', 'description' => 'Categoría del evento'],
        'texto' => ['type' => 'string', 'description' => 'Contenido en markdown'],
        'imagen' => ['type' => 'string', 'description' => 'Ruta o URL de la imagen'],
        'published_at' => ['type' => 'string', 'description' => 'Fecha de publicación (YYYY-MM-DD)'],
        'fecha_inicio' => ['type' => 'string', 'description' => 'Fecha de inicio (YYYY-MM-DD)'],
        'fecha_fin' => ['type' => 'string', 'description' => 'Fecha de fin (YYYY-MM-DD)'],
        'hora_inicio' => ['type' => 'string', 'description' => 'Hora de inicio (HH:MM)'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
        'centro_id' => ['type' => 'int', 'description' => 'ID del centro asociado'],
        'sala_id' => ['type' => 'int', 'description' => 'ID de la sala asociada'],
        'equipo_id' => ['type' => 'int', 'description' => 'ID del equipo organizador'],
    ],
    'grupo' => [
        'nombre' => ['type' => 'string', 'description' => 'Nombre del grupo'],
        'slug' => ['type' => 'string', 'description' => 'Slug único'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
    ],
    'guia' => [
        'nombre' => ['type' => 'string', 'description' => 'Nombre de la guía'],
        'slug' => ['type' => 'string', 'description' => 'Slug único'],
        'categoria' => ['type' => 'string', 'description' => 'Categoría de la guía'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'texto' => ['type' => 'string', 'description' => 'Contenido en markdown'],
        'imagen' => ['type' => 'string', 'description' => 'Ruta o URL de la imagen'],
        'bibliografia' => ['type' => 'string', 'description' => 'Bibliografía asociada'],
        'libros' => ['type' => 'string', 'description' => 'Libros asociados'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
    ],
    'informe' => [
        'titulo' => ['type' => 'string', 'description' => 'Título del informe'],
        'categoria' => ['type' => 'string', 'description' => 'Categoría del informe'],
        'equipo_id' => ['type' => 'int', 'description' => 'ID del equipo asociado'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'texto' => ['type' => 'string', 'description' => 'Contenido en markdown'],
        'audios' => ['type' => 'array', 'description' => 'Lista de archivos de audio asociados'],
        'archivos' => ['type' => 'array', 'description' => 'Lista de archivos adjuntos'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
    ],
    'libro' => [
        'titulo' => ['type' => 'string', 'description' => 'Título del libro'],
        'slug' => ['type' => 'string', 'description' => 'Slug único'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'categoria' => ['type' => 'string', 'description' => 'Categoría del libro'],
        'imagen' => ['type' => 'string', 'description' => 'Ruta o URL de la imagen'],
        'edicion' => ['type' => 'string', 'description' => 'Edición del libro'],
        'paginas' => ['type' => 'int', 'description' => 'Número de páginas'],
        'pdf' => ['type' => 'string', 'description' => 'Ruta o URL del PDF'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
    ],
    'lugar' => [
        'nombre' => ['type' => 'string', 'description' => 'Nombre del lugar'],
        'slug' => ['type' => 'string', 'description' => 'Slug único'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'categoria' => ['type' => 'string', 'description' => 'Categoría del lugar'],
        'imagen' => ['type' => 'string', 'description' => 'Ruta o URL de la imagen'],
        'texto' => ['type' => 'string', 'description' => 'Contenido en markdown'],
        'libros' => ['type' => 'string', 'description' => 'Libros asociados'],
        'relacionados' => ['type' => 'string', 'description' => 'Lugares relacionados'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
    ],
    'meditacion' => [
        'titulo' => ['type' => 'string', 'description' => 'Título de la meditación'],
        'slug' => ['type' => 'string', 'description' => 'Slug único'],
        'categoria' => ['type' => 'string', 'description' => 'Categoría de la meditación'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'texto' => ['type' => 'string', 'description' => 'Contenido en markdown'],
        'audios' => ['type' => 'array', 'description' => 'Lista de archivos de audio asociados'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
    ],
    'normativa' => [
        'titulo' => ['type' => 'string', 'description' => 'Título de la normativa'],
        'slug' => ['type' => 'string', 'description' => 'Slug único'],
        'descripcion' => ['type' => 'string', 'description' => 'Descripción breve'],
        'texto' => ['type' => 'string', 'description' => 'Contenido en markdown'],
        'published_at' => ['type' => 'string', 'description' => 'Fecha de publicación (YYYY-MM-DD)'],
        'visibilidad' => ['type' => 'string', 'description' => '"P"=publicado, "B"=borrador'],
    ],
];
